//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_CARDFRAUDSTATUSENUM
#define APIMATIC_CARDFRAUDSTATUSENUM
 
enum CardFraudStatusEnum
{
        CardFraudStatusCURRENTCARDACTIVE, //TODO: Write general description for this method
        CardFraudStatusTEMP, //TODO: Write general description for this method
};

#endif