//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "CardFraudStatusEnumHelper.h"

/**
* Helper class implementation for CardFraudStatusEnum to NSString conversion
*/
@implementation CardFraudStatusEnumHelper

+(id) stringFromCardFraudStatusEnum:(enum CardFraudStatusEnum) cardFraudStatusEnum withDefault: (id) defaultValue
{
    switch(cardFraudStatusEnum)
    {
        case CardFraudStatusCURRENTCARDACTIVE:
            return @"CURRENT_CARD_ACTIVE";

        case CardFraudStatusTEMP:
            return @"TEMP";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromCardFraudStatusEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [CardFraudStatusEnumHelper stringFromCardFraudStatusEnum:(enum CardFraudStatusEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum CardFraudStatusEnum) cardFraudStatusEnumFromString:(NSString*) strValue
{
    NSArray* CardFraudStatusEnumArray = [NSArray arrayWithObjects:
                                        @"CURRENT_CARD_ACTIVE",
                                        @"TEMP",
                                        nil];

    return (enum CardFraudStatusEnum) [CardFraudStatusEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) cardFraudStatusEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ CardFraudStatusEnumHelper cardFraudStatusEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end