//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_CHALLENGE
#define APIMATIC_CHALLENGE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "TypeEnum.h"
#import "TypeEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol Challenge
@end

@interface Challenge : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSUUID* mid;

/**
* TODO: Write general description for this field
*/
@property NSUUID* transactionId;

/**
* TODO: Write general description for this field
*/
@property NSString* memonotes;

/**
* TODO: Write general description for this field
*/
@property NSString* reason;

/**
* TODO: Write general description for this field
*/
@property enum TypeEnum type;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif