//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "CreditCard.h"

@implementation CreditCard

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize number;

/**
* TODO: Write general description for this method
*/
@synthesize blocked;

/**
* TODO: Write general description for this method
*/
@synthesize replacement;

/**
* TODO: Write general description for this method
*/
@synthesize transactions;

-(id)init
{
    if (self = [super init])
    {
        self.blocked = NO;
        self.replacement = NO;
    }
    return self;
}



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"number": @"number",
        @"blocked": @"blocked",
        @"replacement": @"replacement",
        @"transactions": @"transactions"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end