//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DEBITCARD
#define APIMATIC_DEBITCARD

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "StateEnum.h"
#import "StateEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol DebitCard
@end

@interface DebitCard : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSUUID* mid;

/**
* TODO: Write general description for this field
*/
@property NSNumber* number;

/**
* TODO: Write general description for this field
*/
@property NSDate* expiration;

/**
* TODO: Write general description for this field
*/
@property NSString* firstName;

/**
* TODO: Write general description for this field
*/
@property NSString* middleName;

/**
* TODO: Write general description for this field
*/
@property NSString* lastName;

/**
* TODO: Write general description for this field
*/
@property NSNumber* phoneNumber;

/**
* TODO: Write general description for this field
*/
@property NSString* address;

/**
* TODO: Write general description for this field
*/
@property NSString* address2;

/**
* TODO: Write general description for this field
*/
@property NSString* city;

/**
* TODO: Write general description for this field
*/
@property enum StateEnum state;

/**
* TODO: Write general description for this field
*/
@property NSString* country;

/**
* TODO: Write general description for this field
*/
@property NSDate* dateIssued;

/**
* TODO: Write general description for this field
*/
@property BOOL frozen;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif