//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DISPUTESTATUSENUMHELPER
#define APIMATIC_DISPUTESTATUSENUMHELPER

#include "DisputeStatusEnum.h"

/**
* Helper class interface for DisputeStatusEnum to NSString conversion
*/
@interface DisputeStatusEnumHelper : NSObject

+(id) stringFromDisputeStatusEnum:(enum DisputeStatusEnum) disputeStatusEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromDisputeStatusEnumArray:(NSArray<NSNumber*>*) array;


+(enum DisputeStatusEnum) disputeStatusEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) disputeStatusEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif