//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "DisputeStatusEnumHelper.h"

/**
* Helper class implementation for DisputeStatusEnum to NSString conversion
*/
@implementation DisputeStatusEnumHelper

+(id) stringFromDisputeStatusEnum:(enum DisputeStatusEnum) disputeStatusEnum withDefault: (id) defaultValue
{
    switch(disputeStatusEnum)
    {
        case DisputeStatusTEMP:
            return @"TEMP";

        case DisputeStatusTEMP2:
            return @"TEMP2";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromDisputeStatusEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [DisputeStatusEnumHelper stringFromDisputeStatusEnum:(enum DisputeStatusEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum DisputeStatusEnum) disputeStatusEnumFromString:(NSString*) strValue
{
    NSArray* DisputeStatusEnumArray = [NSArray arrayWithObjects:
                                        @"TEMP",
                                        @"TEMP2",
                                        nil];

    return (enum DisputeStatusEnum) [DisputeStatusEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) disputeStatusEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ DisputeStatusEnumHelper disputeStatusEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end