//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DISPUTESTATUSENUM
#define APIMATIC_DISPUTESTATUSENUM
 
enum DisputeStatusEnum
{
        DisputeStatusTEMP, //TODO: Write general description for this method
        DisputeStatusTEMP2, //TODO: Write general description for this method
};

#endif