//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "APIError.h"
#import "HttpContext.h"



@interface ErrorErrorException : APIError
 
 /**
* TODO: Write general description for this field
*/
@property NSString* code;

/**
* TODO: Write general description for this field
*/
@property NSString* message;

- (ErrorErrorException*) initWithReason: (NSString*) reason
                                  andContext: (HttpContext*) context;

@end