//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "PaymentMethod.h"

@implementation PaymentMethod

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize type;

 /**
 * For serialization of enum Type1Enum type property as NSString*
 */
-(id) JSONObjectForType
{
     
    return [Type1EnumHelper stringFromType1Enum:(enum Type1Enum) type withDefault: nil];

}

/**
 * For deserialization of enum Type1Enum type property from NSString*
 */
 
-(void)setTypeWithNSString:(NSString*) strValue
{
    type = [Type1EnumHelper type1EnumFromString:(NSString*) strValue];
}




/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"type": @"type"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end