//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_PAYMENTMETHOD
#define APIMATIC_PAYMENTMETHOD

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Type1Enum.h"
#import "Type1EnumHelper.h"


//protocol defined for deserialization of JSON
@protocol PaymentMethod
@end

@interface PaymentMethod : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSUUID* mid;

/**
* TODO: Write general description for this field
*/
@property enum Type1Enum type;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif