//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_SCHEDULEDPAYMENT
#define APIMATIC_SCHEDULEDPAYMENT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Type2Enum.h"
#import "Type2EnumHelper.h"
#import "PaymentMethod.h"


//protocol defined for deserialization of JSON
@protocol ScheduledPayment
@end

@interface ScheduledPayment : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSUUID* mid;

/**
* TODO: Write general description for this field
*/
@property NSString* date;

/**
* TODO: Write general description for this field
*/
@property NSNumber* amount;

/**
* TODO: Write general description for this field
*/
@property NSNumber* source;

/**
* TODO: Write general description for this field
*/
@property enum Type2Enum type;

/**
* TODO: Write general description for this field
*/
@property PaymentMethod* method;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif