//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "ScheduledPayment.h"

@implementation ScheduledPayment

/**
* TODO: Write general description for this method
*/
@synthesize mid;

/**
* TODO: Write general description for this method
*/
@synthesize date;

/**
* TODO: Write general description for this method
*/
@synthesize amount;

/**
* TODO: Write general description for this method
*/
@synthesize source;

/**
* TODO: Write general description for this method
*/
@synthesize type;

/**
* TODO: Write general description for this method
*/
@synthesize method;

 /**
 * For serialization of enum Type2Enum type property as NSString*
 */
-(id) JSONObjectForType
{
     
    return [Type2EnumHelper stringFromType2Enum:(enum Type2Enum) type withDefault: nil];

}

/**
 * For deserialization of enum Type2Enum type property from NSString*
 */
 
-(void)setTypeWithNSString:(NSString*) strValue
{
    type = [Type2EnumHelper type2EnumFromString:(NSString*) strValue];
}




/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"id": @"mid",
        @"date": @"date",
        @"amount": @"amount",
        @"source": @"source",
        @"type": @"type",
        @"method": @"method"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end