//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_SELECTIONENUMHELPER
#define APIMATIC_SELECTIONENUMHELPER

#include "SelectionEnum.h"

/**
* Helper class interface for SelectionEnum to NSString conversion
*/
@interface SelectionEnumHelper : NSObject

+(id) stringFromSelectionEnum:(enum SelectionEnum) selectionEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromSelectionEnumArray:(NSArray<NSNumber*>*) array;


+(enum SelectionEnum) selectionEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) selectionEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif