//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_SELECTIONENUM
#define APIMATIC_SELECTIONENUM
 
enum SelectionEnum
{
        SelectionFullamount, //TODO: Write general description for this method
        SelectionMinimum, //TODO: Write general description for this method
        SelectionFixed, //TODO: Write general description for this method
};

#endif