//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "SelectionEnumHelper.h"

/**
* Helper class implementation for SelectionEnum to NSString conversion
*/
@implementation SelectionEnumHelper

+(id) stringFromSelectionEnum:(enum SelectionEnum) selectionEnum withDefault: (id) defaultValue
{
    switch(selectionEnum)
    {
        case SelectionFullamount:
            return @"full-amount";

        case SelectionMinimum:
            return @"minimum";

        case SelectionFixed:
            return @"fixed";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromSelectionEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [SelectionEnumHelper stringFromSelectionEnum:(enum SelectionEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum SelectionEnum) selectionEnumFromString:(NSString*) strValue
{
    NSArray* SelectionEnumArray = [NSArray arrayWithObjects:
                                        @"full-amount",
                                        @"minimum",
                                        @"fixed",
                                        nil];

    return (enum SelectionEnum) [SelectionEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) selectionEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ SelectionEnumHelper selectionEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end