//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "SortByEnumHelper.h"

/**
* Helper class implementation for SortByEnum to NSString conversion
*/
@implementation SortByEnumHelper

+(id) stringFromSortByEnum:(enum SortByEnum) sortByEnum withDefault: (id) defaultValue
{
    switch(sortByEnum)
    {
        case SortByEnumTitleasc:
            return @"title.asc";

        case SortByEnumTitledesc:
            return @"title.desc";

        case SortByEnumDateasc:
            return @"date.asc";

        case SortByEnumDatedesc:
            return @"date.desc";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromSortByEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [SortByEnumHelper stringFromSortByEnum:(enum SortByEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum SortByEnum) sortByEnumFromString:(NSString*) strValue
{
    NSArray* SortByEnumArray = [NSArray arrayWithObjects:
                                        @"title.asc",
                                        @"title.desc",
                                        @"date.asc",
                                        @"date.desc",
                                        nil];

    return (enum SortByEnum) [SortByEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) sortByEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ SortByEnumHelper sortByEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end