//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_SORTBYENUMHELPER
#define APIMATIC_SORTBYENUMHELPER

#include "SortByEnum.h"

/**
* Helper class interface for SortByEnum to NSString conversion
*/
@interface SortByEnumHelper : NSObject

+(id) stringFromSortByEnum:(enum SortByEnum) sortByEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromSortByEnumArray:(NSArray<NSNumber*>*) array;


+(enum SortByEnum) sortByEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) sortByEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif