//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_SORTBYENUM
#define APIMATIC_SORTBYENUM
 
enum SortByEnum
{
        SortByEnumTitleasc, //TODO: Write general description for this method
        SortByEnumTitledesc, //TODO: Write general description for this method
        SortByEnumDateasc, //TODO: Write general description for this method
        SortByEnumDatedesc, //TODO: Write general description for this method
};

#endif