//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATEENUMHELPER
#define APIMATIC_STATEENUMHELPER

#include "StateEnum.h"

/**
* Helper class interface for StateEnum to NSString conversion
*/
@interface StateEnumHelper : NSObject

+(id) stringFromStateEnum:(enum StateEnum) stateEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromStateEnumArray:(NSArray<NSNumber*>*) array;


+(enum StateEnum) stateEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) stateEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif