//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "StateEnumHelper.h"

/**
* Helper class implementation for StateEnum to NSString conversion
*/
@implementation StateEnumHelper

+(id) stringFromStateEnum:(enum StateEnum) stateEnum withDefault: (id) defaultValue
{
    switch(stateEnum)
    {
        case StateAL:
            return @"AL";

        case StateCA:
            return @"CA";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromStateEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [StateEnumHelper stringFromStateEnum:(enum StateEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum StateEnum) stateEnumFromString:(NSString*) strValue
{
    NSArray* StateEnumArray = [NSArray arrayWithObjects:
                                        @"AL",
                                        @"CA",
                                        nil];

    return (enum StateEnum) [StateEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) stateEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ StateEnumHelper stateEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end