//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUSENUM
#define APIMATIC_STATUSENUM
 
enum StatusEnum
{
        StatusACCEPTED, //TODO: Write general description for this method
        StatusDECLINED, //TODO: Write general description for this method
        StatusPENDING, //TODO: Write general description for this method
        StatusDISPUTED, //TODO: Write general description for this method
};

#endif