//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATEENUM
#define APIMATIC_STATEENUM
 
enum StateEnum
{
        StateAL, //TODO: Write general description for this method
        StateCA, //TODO: Write general description for this method
};

#endif