//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRANSACTION
#define APIMATIC_TRANSACTION

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "StatusEnum.h"
#import "StatusEnumHelper.h"
#import "DisputeStatusEnum.h"
#import "DisputeStatusEnumHelper.h"
#import "TransactionTypeEnum.h"
#import "TransactionTypeEnumHelper.h"
#import "TransactionTypeFormattedEnum.h"
#import "TransactionTypeFormattedEnumHelper.h"
#import "CardFraudStatusEnum.h"
#import "CardFraudStatusEnumHelper.h"
#import "Merchant.h"
#import "Cashback.h"
#import "Challenge.h"


//protocol defined for deserialization of JSON
@protocol Transaction
@end

@interface Transaction : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSUUID* mid;

/**
* TODO: Write general description for this field
*/
@property NSString* description;

/**
* TODO: Write general description for this field
*/
@property NSNumber* code;

/**
* TODO: Write general description for this field
*/
@property enum StatusEnum status;

/**
* TODO: Write general description for this field
*/
@property enum DisputeStatusEnum disputeStatus;

/**
* TODO: Write general description for this field
*/
@property BOOL disputeEligibility;

/**
* TODO: Write general description for this field
*/
@property enum TransactionTypeEnum transactionType;

/**
* TODO: Write general description for this field
*/
@property enum TransactionTypeFormattedEnum transactionTypeFormatted;

/**
* TODO: Write general description for this field
*/
@property enum CardFraudStatusEnum cardFraudStatus;

/**
* TODO: Write general description for this field
*/
@property NSNumber* cardLast4Digits;

/**
* TODO: Write general description for this field
*/
@property NSString* metaData;

/**
* TODO: Write general description for this field
*/
@property Merchant* merchant;

/**
* TODO: Write general description for this field
*/
@property NSNumber* amount;

/**
* TODO: Write general description for this field
*/
@property NSString* dateTransaction;

/**
* TODO: Write general description for this field
*/
@property NSString* datePosted;

/**
* TODO: Write general description for this field
*/
@property NSUUID* creditCard;

/**
* TODO: Write general description for this field
*/
@property Cashback* cashback;

/**
* TODO: Write general description for this field
*/
@property NSArray<Challenge> * challenges;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif