//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRANSACTIONTYPEFORMATTEDENUM
#define APIMATIC_TRANSACTIONTYPEFORMATTEDENUM
 
enum TransactionTypeFormattedEnum
{
        TransactionTypeFormattedEnumRegularPurchase, //TODO: Write general description for this method
        TransactionTypeFormattedTemp, //TODO: Write general description for this method
};

#endif