//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRANSACTIONTYPEFORMATTEDENUMHELPER
#define APIMATIC_TRANSACTIONTYPEFORMATTEDENUMHELPER

#include "TransactionTypeFormattedEnum.h"

/**
* Helper class interface for TransactionTypeFormattedEnum to NSString conversion
*/
@interface TransactionTypeFormattedEnumHelper : NSObject

+(id) stringFromTransactionTypeFormattedEnum:(enum TransactionTypeFormattedEnum) transactionTypeFormattedEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromTransactionTypeFormattedEnumArray:(NSArray<NSNumber*>*) array;


+(enum TransactionTypeFormattedEnum) transactionTypeFormattedEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) transactionTypeFormattedEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif