//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRANSACTIONTYPEENUMHELPER
#define APIMATIC_TRANSACTIONTYPEENUMHELPER

#include "TransactionTypeEnum.h"

/**
* Helper class interface for TransactionTypeEnum to NSString conversion
*/
@interface TransactionTypeEnumHelper : NSObject

+(id) stringFromTransactionTypeEnum:(enum TransactionTypeEnum) transactionTypeEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromTransactionTypeEnumArray:(NSArray<NSNumber*>*) array;


+(enum TransactionTypeEnum) transactionTypeEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) transactionTypeEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif