//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TRANSACTIONTYPEENUM
#define APIMATIC_TRANSACTIONTYPEENUM
 
enum TransactionTypeEnum
{
        TransactionTypeEnumRegularPurchase, //TODO: Write general description for this method
        TransactionTypeTemp, //TODO: Write general description for this method
};

#endif