//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "TransactionTypeFormattedEnumHelper.h"

/**
* Helper class implementation for TransactionTypeFormattedEnum to NSString conversion
*/
@implementation TransactionTypeFormattedEnumHelper

+(id) stringFromTransactionTypeFormattedEnum:(enum TransactionTypeFormattedEnum) transactionTypeFormattedEnum withDefault: (id) defaultValue
{
    switch(transactionTypeFormattedEnum)
    {
        case TransactionTypeFormattedEnumRegularPurchase:
            return @"Regular Purchase";

        case TransactionTypeFormattedTemp:
            return @"Temp";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromTransactionTypeFormattedEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [TransactionTypeFormattedEnumHelper stringFromTransactionTypeFormattedEnum:(enum TransactionTypeFormattedEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum TransactionTypeFormattedEnum) transactionTypeFormattedEnumFromString:(NSString*) strValue
{
    NSArray* TransactionTypeFormattedEnumArray = [NSArray arrayWithObjects:
                                        @"Regular Purchase",
                                        @"Temp",
                                        nil];

    return (enum TransactionTypeFormattedEnum) [TransactionTypeFormattedEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) transactionTypeFormattedEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ TransactionTypeFormattedEnumHelper transactionTypeFormattedEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end