//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "Type2EnumHelper.h"

/**
* Helper class implementation for Type2Enum to NSString conversion
*/
@implementation Type2EnumHelper

+(id) stringFromType2Enum:(enum Type2Enum) type2Enum withDefault: (id) defaultValue
{
    switch(type2Enum)
    {
        case Type2AUTOPAY:
            return @"AUTOPAY";

        case Type2MANUAL:
            return @"MANUAL";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromType2EnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [Type2EnumHelper stringFromType2Enum:(enum Type2Enum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum Type2Enum) type2EnumFromString:(NSString*) strValue
{
    NSArray* Type2EnumArray = [NSArray arrayWithObjects:
                                        @"AUTOPAY",
                                        @"MANUAL",
                                        nil];

    return (enum Type2Enum) [Type2EnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) type2EnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ Type2EnumHelper type2EnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end