//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TYPEENUM
#define APIMATIC_TYPEENUM
 
enum TypeEnum
{
        TypeDISPUTE, //TODO: Write general description for this method
        TypeFRAUD, //TODO: Write general description for this method
};

#endif