//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TYPE1ENUM
#define APIMATIC_TYPE1ENUM
 
enum Type1Enum
{
        Type1DebitCard, //TODO: Write general description for this method
        Type1Ach, //TODO: Write general description for this method
};

#endif