//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "Type1EnumHelper.h"

/**
* Helper class implementation for Type1Enum to NSString conversion
*/
@implementation Type1EnumHelper

+(id) stringFromType1Enum:(enum Type1Enum) type1Enum withDefault: (id) defaultValue
{
    switch(type1Enum)
    {
        case Type1DebitCard:
            return @"debit_card";

        case Type1Ach:
            return @"ach";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromType1EnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [Type1EnumHelper stringFromType1Enum:(enum Type1Enum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum Type1Enum) type1EnumFromString:(NSString*) strValue
{
    NSArray* Type1EnumArray = [NSArray arrayWithObjects:
                                        @"debit_card",
                                        @"ach",
                                        nil];

    return (enum Type1Enum) [Type1EnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) type1EnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ Type1EnumHelper type1EnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end