//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TYPE1ENUMHELPER
#define APIMATIC_TYPE1ENUMHELPER

#include "Type1Enum.h"

/**
* Helper class interface for Type1Enum to NSString conversion
*/
@interface Type1EnumHelper : NSObject

+(id) stringFromType1Enum:(enum Type1Enum) type1Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromType1EnumArray:(NSArray<NSNumber*>*) array;


+(enum Type1Enum) type1EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) type1EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif