//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TYPE2ENUM
#define APIMATIC_TYPE2ENUM
 
enum Type2Enum
{
        Type2AUTOPAY, //TODO: Write general description for this method
        Type2MANUAL, //TODO: Write general description for this method
};

#endif