//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TYPE2ENUMHELPER
#define APIMATIC_TYPE2ENUMHELPER

#include "Type2Enum.h"

/**
* Helper class interface for Type2Enum to NSString conversion
*/
@interface Type2EnumHelper : NSObject

+(id) stringFromType2Enum:(enum Type2Enum) type2Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromType2EnumArray:(NSArray<NSNumber*>*) array;


+(enum Type2Enum) type2EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) type2EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif