//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "TypeEnumHelper.h"

/**
* Helper class implementation for TypeEnum to NSString conversion
*/
@implementation TypeEnumHelper

+(id) stringFromTypeEnum:(enum TypeEnum) typeEnum withDefault: (id) defaultValue
{
    switch(typeEnum)
    {
        case TypeDISPUTE:
            return @"DISPUTE";

        case TypeFRAUD:
            return @"FRAUD";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromTypeEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [TypeEnumHelper stringFromTypeEnum:(enum TypeEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum TypeEnum) typeEnumFromString:(NSString*) strValue
{
    NSArray* TypeEnumArray = [NSArray arrayWithObjects:
                                        @"DISPUTE",
                                        @"FRAUD",
                                        nil];

    return (enum TypeEnum) [TypeEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) typeEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ TypeEnumHelper typeEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end