//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_USER
#define APIMATIC_USER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "UserAutopay.h"


//protocol defined for deserialization of JSON
@protocol User
@end

@interface User : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSUUID* mid;

/**
* TODO: Write general description for this field
*/
@property NSString* firstName;

/**
* TODO: Write general description for this field
*/
@property NSString* lastName;

/**
* TODO: Write general description for this field
*/
@property NSString* email;

/**
* TODO: Write general description for this field
*/
@property BOOL paperlessStatements;

/**
* TODO: Write general description for this field
*/
@property UserAutopay* autopay;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif