//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_USERAUTOPAY
#define APIMATIC_USERAUTOPAY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "SelectionEnum.h"
#import "SelectionEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol UserAutopay
@end

@interface UserAutopay : JSONModel

/**
* TODO: Write general description for this field
*/
@property BOOL enabled;

/**
* TODO: Write general description for this field
*/
@property enum SelectionEnum selection;

/**
* TODO: Write general description for this field
*/
@property NSNumber* amount;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif