//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"
#import "Ach.h"
#import "SortByEnum.h"
#import "SortByEnumHelper.h"
#import "ErrorErrorException.h"

@interface AchController : BaseController

/**
* Completion block definition for asynchronous call to getaches */
typedef void (^CompletedGetaches)(BOOL success, HttpContext* context, NSArray<Ach> * response, NSError* error);

/**
* List of aches.
* @param    limit    Optional parameter: Amount of records to return
* @param    startingAfter    Optional parameter: The Object ID from which to continue obtaining items from the list
* @param    endingBefore    Optional parameter: The Object ID from which to definitely end the list segment
* @param    q    Optional parameter: main query parameter
* @param    sortBy    Optional parameter: main sort parameter
*/
- (void) getachesAsyncWithLimit:(NSNumber*) limit
                startingAfter:(NSNumber*) startingAfter
                endingBefore:(NSNumber*) endingBefore
                q:(NSString*) q
                sortBy:(enum SortByEnum) sortBy
                completionBlock:(CompletedGetaches) onCompleted;

/**
* Completion block definition for asynchronous call to addach */
typedef void (^CompletedPostAddach)(BOOL success, HttpContext* context, NSArray<Ach> * response, NSError* error);

/**
* Create a new ach
* @param    body    Optional parameter: Example: 
*/
- (void) addachAsyncWithBody:(Ach*) body
                completionBlock:(CompletedPostAddach) onCompleted;

/**
* Completion block definition for asynchronous call to getach */
typedef void (^CompletedGetach)(BOOL success, HttpContext* context, NSArray<Ach> * response, NSError* error);

/**
* Obtain a single ach by id
* @param    mid    Required parameter: Numeric ID of the ach to get
*/
- (void) getachAsyncWithId:(NSUUID*) mid
                completionBlock:(CompletedGetach) onCompleted;

/**
* Completion block definition for asynchronous call to deleteach */
typedef void (^CompletedDeleteach)(BOOL success, HttpContext* context, NSArray<Ach> * response, NSError* error);

/**
* Deletes a ach
* @param    mid    Required parameter: ID of the ach to delete
*/
- (void) deleteachAsyncWithId:(int) mid
                completionBlock:(CompletedDeleteach) onCompleted;

/**
* Completion block definition for asynchronous call to updateach */
typedef void (^CompletedPatchUpdateach)(BOOL success, HttpContext* context, NSArray<Ach> * response, NSError* error);

/**
* Update an existing ach
* @param    mid    Required parameter: Numeric ID of the ach to update
* @param    body    Optional parameter: Example: 
*/
- (void) updateachAsyncWithId:(NSUUID*) mid
                body:(Ach*) body
                completionBlock:(CompletedPatchUpdateach) onCompleted;

@end