//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"
#import "DebitCard.h"
#import "SortByEnum.h"
#import "SortByEnumHelper.h"
#import "ErrorErrorException.h"

@interface DebitCardController : BaseController

/**
* Completion block definition for asynchronous call to getdebit_cards */
typedef void (^CompletedGetdebitCards)(BOOL success, HttpContext* context, NSArray<DebitCard> * response, NSError* error);

/**
* List of debit_cards.
* @param    limit    Optional parameter: Amount of records to return
* @param    startingAfter    Optional parameter: The Object ID from which to continue obtaining items from the list
* @param    endingBefore    Optional parameter: The Object ID from which to definitely end the list segment
* @param    q    Optional parameter: main query parameter
* @param    sortBy    Optional parameter: main sort parameter
*/
- (void) getdebitCardsAsyncWithLimit:(NSNumber*) limit
                startingAfter:(NSNumber*) startingAfter
                endingBefore:(NSNumber*) endingBefore
                q:(NSString*) q
                sortBy:(enum SortByEnum) sortBy
                completionBlock:(CompletedGetdebitCards) onCompleted;

/**
* Completion block definition for asynchronous call to adddebit_card */
typedef void (^CompletedPostAdddebitCard)(BOOL success, HttpContext* context, NSArray<DebitCard> * response, NSError* error);

/**
* Create a new debit_card
* @param    body    Optional parameter: Example: 
*/
- (void) adddebitCardAsyncWithBody:(DebitCard*) body
                completionBlock:(CompletedPostAdddebitCard) onCompleted;

/**
* Completion block definition for asynchronous call to getdebit_card */
typedef void (^CompletedGetdebitCard)(BOOL success, HttpContext* context, NSArray<DebitCard> * response, NSError* error);

/**
* Obtain a single debit_card by id
* @param    mid    Required parameter: Numeric ID of the debit_card to get
*/
- (void) getdebitCardAsyncWithId:(NSUUID*) mid
                completionBlock:(CompletedGetdebitCard) onCompleted;

/**
* Completion block definition for asynchronous call to deletedebit_card */
typedef void (^CompletedDeletedebitCard)(BOOL success, HttpContext* context, NSArray<DebitCard> * response, NSError* error);

/**
* Deletes a debit_card
* @param    mid    Required parameter: ID of the debit_card to delete
*/
- (void) deletedebitCardAsyncWithId:(int) mid
                completionBlock:(CompletedDeletedebitCard) onCompleted;

/**
* Completion block definition for asynchronous call to updatedebit_card */
typedef void (^CompletedPatchUpdatedebitCard)(BOOL success, HttpContext* context, NSArray<DebitCard> * response, NSError* error);

/**
* Update an existing debit_card
* @param    mid    Required parameter: Numeric ID of the debit_card to update
* @param    body    Optional parameter: Example: 
*/
- (void) updatedebitCardAsyncWithId:(NSUUID*) mid
                body:(DebitCard*) body
                completionBlock:(CompletedPatchUpdatedebitCard) onCompleted;

@end