//
//  ConsumerMobile
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://virtserver.swaggerhub.com/jglassenberg/DTest2/1.0.0";

/** Replace the value of XAPIKey with an appropriate value */
NSString* Configuration_XAPIKey = @"";

